version: "3"
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp # Required if you want your server to show up in the community servers tab
      - 127.0.0.1:25575:25575 # RCON port
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211 # Optional but recommended
      - PLAYERS=16 # Optional but recommended
      - SERVER_PASSWORD="worldofpals" # Optional but recommended
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ=UTC
      - ADMIN_PASSWORD="adminPasswordHere" # RCON Password
      - COMMUNITY=false # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      - SERVER_NAME="World of Pals"
      - SERVER_DESCRIPTION=""
    volumes:
      - ./palworld:/palworld/
  palworld-rcon-buddy:
    image: "valamidev/palworld-rcon-buddy:latest"
    environment:
      PALWORLD_SERVER_IP_ADDRESS: "palworld" # This is how you can refference the palworld container
      PALWORLD_RCON_PORT: "25575"
      PALWORLD_RCON_PASSWORD: "adminPasswordHere" # RCON Password
      INFO_CACHE_DURATION_MS: 5000 # By Default /info end-point is cached for 5 seconds
      BEARER_TOKEN: "YOUR_TOKEN"
      PORT: 3000 # RCON-BUDDY port
    ports:
      - "3000:3000"
