name: Copy Testing to Latest
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'The name of the Docker image'
        required: true
        default: 'docker-palworld-dedicated-server-wine'

jobs:
  move_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}:testing

      - name: Tag Docker image
        run: docker tag ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}:testing ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}:latest

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}:latest
